spring:
  datasource:
    url: jdbc:h2:mem:library;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;
    driver-class-name: org.h2.Driver
    username: sa
    password:
    platform: h2
  h2:
    console:
      enabled: true
      path: /h2

